// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace CryptRaiderGameplayTags
{
	/** Player Tags **/
	
		/** Input Tags **/
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ToggleMenu);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_ToggleWeapon);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dodge);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Heal);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Weapon_Light);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Weapon_Heavy);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Sword);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Sword);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget)

	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_Magic)
	
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);
	
		/** Abilities **/
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Interact);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Dodge);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_TargetLock);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Magic);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_RecoverStamina);
	
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_SpecialWeaponAbility_Light_Axe);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_SpecialWeaponAbility_Heavy_Axe);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Sword);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Sword);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_SpecialWeaponAbility_Light_Sword);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_SpecialWeaponAbility_Heavy_Sword);
	
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);

		/** Events **/
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_EquipLightWeapon);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnequipLightWeapon);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_EquipHeavyWeapon);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UnequipHeavyWeapon);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwapWeapon);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessfulBlock);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Left);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Right);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_ActivateMagic);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_UseStamina);



		/** Statuses **/
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToNextAttack)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Dodging);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Attacking);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Inspecting);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_TargetLock);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Stamina_None);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Stamina_NotFull);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Stamina_Full);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Magic_Activating);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Magic_Active);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Magic_Full);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Magic_None);

	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_StaminaRegen);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialWeaponAbility_Light);
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_SpecialWeaponAbility_Heavy);
	
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy)

		
	/** Enemy Tags **/
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Dodge)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_SummonEnemies)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Patrolling)

	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Event_SummonEnemies)

	/** Shared Tags **/
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SpawnProjectile)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_AOE);
	
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_SpecialDamage)

	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_BuffedAttack)
	CRYPTRAIDER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Invincible)
}
